- hosts: myservers
  tasks:
  - name: "Install Nodejs 6.x"
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && apt-get install -y nodejs
    environment:
      http_proxy: ${proxy_server}
      https_proxy: ${proxy_server}
  - name: "Install pm2"
    shell: npm install -g pm2
    environment:
      http_proxy: ${proxy_server}
      https_proxy: ${proxy_server}  